services:
  - type: web
    name: ai-dietary-advisor
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ai-dietary-advisor-db
          property: connectionString
    autoDeploy: true

databases:
  - name: ai-dietary-advisor-db
    databaseName: ai_dietary_advisor
    user: ai_dietary_advisor_user